meta:
  app_id: {{APP_ID}}
  display_name: {{APP_DISPLAY_NAME}}
  version: 1.0.0-dev.1
  vendor: optimizely
  summary: {{APP_SUMMARY}}
  support_url: https://github.com/{{GITHUB_USERNAME}}/{{REPO_NAME}}
  contact_email: {{CONTACT_EMAIL}}
  categories:
    - Opal
  availability:
    - all

runtime: node22

functions:
  opal_tool:
    entry_point: OpalToolFunction
    description: {{TOOL_DESCRIPTION}}
    opal_tool: true
